version: 2.1
jobs:
  checkout:
    working_directory: ~/library
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: [website, docs]
  build:
    working_directory: ~/library/website
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - attach_workspace:
          at: ..
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn run build
      - persist_to_workspace:
          root: .
          paths: build
  deploy:
    working_directory: ~/library/website
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/install
      - aws-cli/setup
      - run: aws s3 sync --size-only --cache-control "max-age=0" --delete build/library/ s3://www.collective.gg/library/
orbs:
  node: circleci/node@1.1
  aws-cli: circleci/aws-cli@0.1.16
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - build:
          requires: [checkout]
      - deploy:
          requires: [build]
          filters:
            branches:
              only: master
